### PR TITLE
Clamp mouse wheel values

### PR DESCRIPTION
**Pull request by devildefu**
Browsers return some abstract value and we need to limit it to 1.0.

### CODE REVIEW

**Comment by liquidev** [comment]
The value returned by browsers isn't actually "abstract". Browsers return the amount of _pixels_ that should be scrolled on the Y axis, but since this is zoom we're talking about, there aren't any pixels to speak of, only scale increments.

I'm not that happy about just clamping the values. macOS for instance will "accelerate" scrolling: the amount scrolled will be greater with each step of the scroll wheel. I'd rather keep that behavior, and supporting that requires us to _not_ clamp the value, as it can accelerate past 1.0.

**Comment by devildefu** [comment]
There is only one problem - scale. What scale are you going to use for this when almost every browser gives some different value? For example, in my case on Chrome this value is around 200, but on Firefox this value already **exceeds 1000**. Making a scale for this will be hard.

**Comment by liquidev** [comment]
Yeah, I know that. I wonder if winit exposes this scale somehow. Looking at browser APIs though, there doesn't seem to be a way of checking how the values are scaled, which is a shame.

I propose that we postpone this until an official wasm version is implemented. At that point we can add a `#[cfg]` checking if we're compiling for wasm, clamping the value then.

**Comment by devildefu** [comment]
Makes sense, I think.

**Comment by liquidev** [comment]
Looks OK I guess. Merging.

**Pull request merged**
